version: '3'
services:
  nginx:
    image: 'nginx:alpine'
    ports:
      - '80:80'
    volumes:
      - './whmcs:/var/www/html'
      - './src:/var/www/html/modules/addons/sso'
      - './nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf'
    networks:
      whmcs:
        ipv4_address: 172.20.0.2
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - php
      - mysql
      - redis
      - mailhog
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: whmcs-8.1
    volumes:
      - './whmcs:/var/www/html'
      - './src:/var/www/html/modules/addons/sso'
      - './php/conf.d/php.ini:/usr/local/etc/php/conf.d/100-custom.ini'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      whmcs:
        ipv4_address: 172.20.0.3
  mysql:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_DATABASE: '${DB_DATABASE:-whmcs}'
      MYSQL_USER: '${DB_USERNAME:-whmcs}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      whmcs:
        ipv4_address: 172.20.0.4
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-password}"]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    networks:
      whmcs:
        ipv4_address: 172.20.0.5
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      whmcs:
        ipv4_address: 172.20.0.6
networks:
  whmcs:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
volumes:
  mysql:
    driver: local
  redis:
    driver: local